version: '3.9'


services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    build:
      context: .
      dockerfile: C:\Users\MF\source\repos\microservices\Evently\src\Evently.Api\Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  evently.database:
    image: postgres:latest
    container_name: Evently.Database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=evently
    volumes: 
    - ./.containers/db:/var/lib/postgresql/data
  