<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\Evently.Common.Domain\Evently.Common.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Policies\" />
      <Folder Include="Users\Models\" />
    </ItemGroup>

</Project>
